### ISSUE TITLE
Json Log framework 

### ISSUE THREAD

**Issue by epmartini** [emartech/escher-suiteapi-js#37]
Hi, 

at the moment, it is using ```logentries-logformat``` that is not compatible with our LAAS.

It would be nice to have the possibilty to choose between ```logentries-logformat``` and ```@emartech/json-logger```.

Thanks 
Patrick

**Comment by drawain** [comment]
Or we can change it to the json logger an release it as a major upgrade

**Comment by epmartini** [comment]
@drawain for me is ok.
